# Generated by Django 6.1 on 2026-08-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ruta',
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id_estacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_estacion', models.IntegerField()),
                ('kilometro', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ruta', models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='core.ruta')),
            ],
            options={
                'db_table': 'estacion',
                'unique_together': {('ruta', 'numero_estacion')},
            },
        ),
        migrations.CreateModel(
            name='Casilla',
            fields=[
                ('id_casilla', models.AutoField(primary_key=True, serialize=False)),
                ('numero_casilla', models.IntegerField()),
                ('estacion', models.ForeignKey(db_column='id_estacion', on_delete=django.db.models.deletion.CASCADE, related_name='casillas', to='core.estacion')),
            ],
            options={
                'db_table': 'casilla',
                'unique_together': {('estacion', 'numero_casilla')},
            },
        ),
    ]
