# Generated by Django 6.1 on 2026-09-20 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('legajo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('es_administrador', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'operador',
            },
        ),
        migrations.CreateModel(
            name='CategoriaVehiculo',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'categoria_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id_estacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_estacion', models.IntegerField()),
                ('kilometro', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'estacion',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ruta',
            },
        ),
        migrations.CreateModel(
            name='Casilla',
            fields=[
                ('id_casilla', models.AutoField(primary_key=True, serialize=False)),
                ('numero_casilla', models.IntegerField()),
                ('estacion', models.ForeignKey(db_column='id_estacion', on_delete=django.db.models.deletion.CASCADE, related_name='casillas', to='core.estacion')),
            ],
            options={
                'db_table': 'casilla',
                'unique_together': {('estacion', 'numero_casilla')},
            },
        ),
        migrations.AddField(
            model_name='estacion',
            name='ruta',
            field=models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='core.ruta'),
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='core.categoriavehiculo')),
            ],
            options={
                'db_table': 'tarifa',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('sentido_cobro', models.CharField(choices=[('NS', 'Norte-Sur'), ('SN', 'Sur-Norte'), ('EO', 'Este-Oeste'), ('OE', 'Oeste-Este')], max_length=2)),
                ('monto_cambio_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inicio_programado', models.DateTimeField()),
                ('fin_programado', models.DateTimeField()),
                ('fecha_hora_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('casilla', models.ForeignKey(db_column='id_casilla', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='core.casilla')),
                ('operador', models.ForeignKey(db_column='legajo_operador', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('numero_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_emision', models.DateTimeField(auto_now_add=True)),
                ('importe_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patente_detectada', models.CharField(blank=True, max_length=15, null=True)),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.tarifa')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.turno')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.AlterUniqueTogether(
            name='estacion',
            unique_together={('ruta', 'numero_estacion')},
        ),
    ]
