# Generated by Django 6.1 on 2026-08-27 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('sentido_cobro', models.CharField(choices=[('NS', 'Norte-Sur'), ('SN', 'Sur-Norte'), ('EO', 'Este-Oeste'), ('OE', 'Oeste-Este')], max_length=2)),
                ('monto_cambio_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inicio_programado', models.DateTimeField()),
                ('fin_programado', models.DateTimeField()),
                ('fecha_hora_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('casilla', models.ForeignKey(db_column='id_casilla', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.casilla')),
                ('operador', models.ForeignKey(db_column='legajo_operador', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'turno',
            },
        ),
    ]
