# Generated by Django 6.1 on 2026-08-29 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='operador',
            field=models.ForeignKey(db_column='legajo_operador', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='usuarios.operador'),
        ),
    ]
