# Generated by Django 6.1 on 2026-08-29 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0002_alter_turno_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVehiculo',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='ventas.categoriavehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('numero_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_emision', models.DateTimeField(auto_now_add=True)),
                ('importe_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patente_detectada', models.CharField(blank=True, max_length=15, null=True)),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.tarifa')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='turnos.turno')),
            ],
        ),
    ]
